### ISSUE TITLE
Use of DIND for CI

### ISSUE THREAD

**Issue by spohnan** [mesosphere/dcos-jenkins-dind-agent#1]
There was a post some months back warning of several possible pitfalls to using the DIND approach for CI and recommended mounting the container host socket instead - https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ my question is about the design decisions that drove your implementation to use DIND.

**Comment by ghost** [comment]
Hey @spohnan, thanks for the question!

In general, I agree with that post: that bind-mounting the socket into the container allows you to use things like the Docker cache on the host and generally results in a nicer user experience. However, there's a couple major problems with doing that in the Mesos world:
1. _Orphaned containers_—if you bind-mount the socket from the Docker daemon into the container running Jenkins' `slave.jar` and something happens to the Jenkins agent (loses connection to the master, crashes, etc) there's a non-zero chance that any Docker image builds or running containers started by the first container will be orphaned and run forever (or at least until the next reboot). Mesos will have no way to detect these, and it will lead to an inconsistent state on your agent(s) that will need to be detected and cleaned up by other out-of-band tooling.
2. _Circumventing resource isolation and monitoring_—bind-mounting the socket from the Docker daemon circumvents Mesos' resource isolation mechanisms, which means that the Docker daemon running on a given Mesos or DCOS agent (outside of Mesos' purview) handles the load of building images and/or running containers as specified in your job configuration. If your resource utilization is high enough on the host (e.g. Jenkins isn't the only thing running, or you run near 100% utilization), you run the risk of running out of CPUs, memory, and/or disk, making troubleshooting more difficult.

We get around each of these by providing a Docker-in-Docker image that actually runs the daemon inside of the container launched by the Jenkins Mesos plugin. This way, the image build process happens within the parent container, and the parent container can be garbage collected along with all of the remnants of the build process. If the parent container crashes or exceeds its allocated resources and is killed, anything running inside of it (including the child Docker daemon) is killed along with it. We understand that this has the negative side-effect of not being able to utilize the host's Docker cache, but does so at the benefit of ensuring a clean build environment every time.

Now, it's worth noting that this is just the _default_ behavior; we [suggest that our users build custom Jenkins agent images based on the needs of their environment](https://docs.mesosphere.com/usage/managing-services/velocity/creating-custom-build-agents/). The approach I explained here won't work for everyone, but it does provide a decent out-of-the-box experience.

I hope that helps!

**Comment by spohnan** [comment]
@rji Quite a number of tradeoffs to balance, thank you for sharing the counterpoints in a Mesos environment.

**Comment by karlkfi** [comment]
For posterity, one more reason to use DinD:

If you host mount the docker socket then you can no longer host mount anything from inside the parent container into a child container. Child containers will actually be sibling containers with no shared directory path. In the context of Jenkins this means that CI builds won't be able to pass files into containers they create.
