### ISSUE TITLE
DIND agent behind corporate proxy

### ISSUE THREAD

**Issue by antoine-voiry** [mesosphere/dcos-jenkins-dind-agent#14]
All,
My DCOS is running behind a corporate proxy and is configured for proxy.
The docker is running with proxy setup on each agent and can pull image from internal repository.
The slave docker jenkins started is not getting accessed to the internet to build anything.

Is there anyway the slave can inherit from the setting of the master?

Step to reproduce on any agent
sudo docker run hello-world => that works
sudo docker run --privileged mesosphere/jenkins-dind:0.3.1 wrapper.sh "docker run hello-world" => That will crash with error Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate is valid for FG3K6C3A13800607, not index.docker.io.

Antoine

**Comment by ssk2** [comment]
Hi @antoine-voiry, I answered your question on StackOverflow: http://stackoverflow.com/a/41109738/948993. Please see that response and let me know how you get on :).
